---
- name: install nfs package
  package: nfs-utils
  state: present

- name: create diretory mount point
  file:
    path: /mnt/nfs-mnt
    state: directory
    mode: 0777

- name: mount an nfs volume
  mount:
     src: "{{ mynfs }}"
     path: "{{ mountpoint }}"
     opts: rw, sync
     state: mounted
     fstype: nfs
